--- #YAML:1.0
name:                Gtk2-Ex-DateSpinner
version:             5
abstract:            Date entry widget using spin buttons.
license:             gpl
author:              
    - Kevin Ryde <user42@zip.com.au>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Date::Calc:                    5.0
    Glib::Ex::SignalIds:           0
    Gtk2:                          1.180
    Gtk2::Ex::WidgetBits:          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
optional_features:
    maximum_tests:
        description: Have "make test" do as much as possible.
        requires:
            Test::Weaken: 3
            Test::Pod: 1.00
            Test::NoWarnings: 0
            Parse::CPAN::Meta: 0
            Test::DistManifest: 0
            Test::YAML::Meta: 0
            YAML: 0
            YAML::Syck: 0
            YAML::Tiny: 0
            YAML::XS: 0
no_index:
    directory:
        - devel
        - inc
        - t
resources:
    homepage: http://user42.tuxfamily.org/gtk2-ex-datespinner/index.html
    license: http://www.gnu.org/licenses/gpl.html
